oui

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -12,21 +12,21 @@ jobs:
     container:
       image: ghcr.io/epitech/coding-style-checker:latest
     steps:
-      -name: Checkout Repository
-       uses: actions/checkout@v4
+      - name: Checkout Repository
+        uses: actions/checkout@v4
       
-      -name: Check Coding Style
-      -run: check sh $(pwd) $(pwd)
+      - name: Check Coding Style
+        run: check sh $(pwd) $(pwd)
 
-      -name: Report banana result
-      run:
-        NB_ERROR=$(cat coding-style-reports.log | wc -l)
-        if [ $NB_ERROR -gt 0 ]; then
-          ERRORS=$(cat coding-style-reports.log);
-          echo "Banana found $NB_ERROR error(s)"
-          echo "$ERRORS"
-          exit 1
-        fi
-          echo "Everything is good ! Keep on coding !"
-          exit 0
+      - name: Report banana result
+        run:
+          NB_ERROR=$(cat coding-style-reports.log | wc -l)
+          if [ $NB_ERROR -gt 0 ]; then
+            ERRORS=$(cat coding-style-reports.log);
+            echo "Banana found $NB_ERROR error(s)"
+            echo "$ERRORS"
+            exit 1
+          fi
+            echo "Everything is good ! Keep on coding !"
+            exit 0
 
